from .distance_oracle import DistanceOracleWithFallback, PrecomputedDistanceOracle
from .gap_vrp_solver_v2 import EnrichedGapVRPConfig, EnrichedGapVRPSolver
from .milp_decomp_solver_v1 import EnrichedMILPDecompConfig, EnrichedMILPDecompSolver
from .milp_stochastic_solver_v1 import EnrichedMILPStochasticConfig, EnrichedMILPStochasticSolver
from .legacy_pipeline_bridge_v1 import EnrichedLegacyGapConfig, EnrichedLegacyMILPConfig
from .milp_solver_v2 import EnrichedMILPConfig, EnrichedMILPSolver
from .problem import EnrichedProblem, build_enriched_problem, task_agent_compatible
from .runner_v2 import (
    benchmark_enriched_algorithms,
    solve_enriched_batched_greedy,
    solve_enriched_gap_vrp,
    solve_enriched_legacy_gap_vrp,
    solve_enriched_legacy_milp,
    solve_enriched_milp_adaptive_hardness,
    solve_enriched_milp_ablation_adaptive_k,
    solve_enriched_milp_ablation_baseline,
    solve_enriched_milp_ablation_penalty_sweep,
    solve_enriched_milp_ablation_portfolio,
    solve_enriched_milp_ablation_zone_bundle,
    solve_enriched_milp_batch_cascaded,
    solve_enriched_milp_batch_portfolio,
    solve_enriched_milp_batch_then_milp,
    solve_enriched_milp_critical_first,
    solve_enriched_milp_hybrid_seeded,
    solve_enriched_milp_lexicographic_2stage,
    solve_enriched_milp_lns_rounds,
    solve_enriched_milp_time_windowed,
    solve_enriched_milp_zone_quota,
    solve_enriched_milp_decomposed,
    solve_enriched_milp_stochastic,
    solve_enriched_milp,
    solve_enriched_stochastic_grasp,
    solve_enriched_stochastic_rr,
)
from .stochastic_solver_v2 import (
    EnrichedStochasticConfig,
    EnrichedStochasticGRASPSolver,
    EnrichedStochasticRRSolver,
)
from .types import AssignmentRoute, AgentUsage, EnrichedAgent, EnrichedSolveResult, EnrichedTask

__all__ = [
    "AgentUsage",
    "AssignmentRoute",
    "DistanceOracleWithFallback",
    "EnrichedAgent",
    "EnrichedGapVRPConfig",
    "EnrichedGapVRPSolver",
    "EnrichedMILPConfig",
    "EnrichedMILPDecompConfig",
    "EnrichedMILPDecompSolver",
    "EnrichedMILPStochasticConfig",
    "EnrichedMILPStochasticSolver",
    "EnrichedLegacyGapConfig",
    "EnrichedLegacyMILPConfig",
    "EnrichedMILPSolver",
    "EnrichedProblem",
    "EnrichedSolveResult",
    "EnrichedStochasticConfig",
    "EnrichedStochasticGRASPSolver",
    "EnrichedStochasticRRSolver",
    "EnrichedTask",
    "PrecomputedDistanceOracle",
    "benchmark_enriched_algorithms",
    "build_enriched_problem",
    "solve_enriched_batched_greedy",
    "solve_enriched_gap_vrp",
    "solve_enriched_legacy_gap_vrp",
    "solve_enriched_legacy_milp",
    "solve_enriched_milp_adaptive_hardness",
    "solve_enriched_milp_ablation_adaptive_k",
    "solve_enriched_milp_ablation_baseline",
    "solve_enriched_milp_ablation_penalty_sweep",
    "solve_enriched_milp_ablation_portfolio",
    "solve_enriched_milp_ablation_zone_bundle",
    "solve_enriched_milp_batch_cascaded",
    "solve_enriched_milp_batch_portfolio",
    "solve_enriched_milp_batch_then_milp",
    "solve_enriched_milp_critical_first",
    "solve_enriched_milp_hybrid_seeded",
    "solve_enriched_milp_lexicographic_2stage",
    "solve_enriched_milp_lns_rounds",
    "solve_enriched_milp_time_windowed",
    "solve_enriched_milp_zone_quota",
    "solve_enriched_milp_decomposed",
    "solve_enriched_milp_stochastic",
    "solve_enriched_milp",
    "solve_enriched_stochastic_grasp",
    "solve_enriched_stochastic_rr",
    "task_agent_compatible",
]
