from .dummy import DummySolverResult, run_dummy_solver
from .gap_vrp_alns_solver import GapVRPALNSSolution, solve_real_gap_vrp_alns
from .gap_vrp_saa_solver import GapVRPSAASolution, solve_real_gap_vrp_saa
from .gap_vrp import SolverResult, compare_methods, run_baseline_greedy, run_gap_vrp, select_agents_subset
from .genetic import assign_tasks_genetic
from .milp import assign_tasks_greedy, solve_sandbox_milp
from .real_gap_vrp_solver import solve_real_gap_vrp
from .real_genetic_solver import solve_real_genetic
from .real_milp_ksenya_solver import solve_real_milp_ksenya
from .real_milp_ksenya_decomp_solver import solve_real_milp_ksenya_decomp
from .real_milp_ksenya_knn_solver import solve_real_milp_ksenya_knn
from .real_milp_ksenya_decomp_knn_solver import solve_real_milp_ksenya_decomp_knn
from .real_milp_solver import solve_real_milp
from .real_stochastic_grasp_solver import solve_real_stochastic_grasp
from .real_stochastic_rr_solver import solve_real_stochastic_rr
from .enriched import (
    EnrichedGapVRPConfig,
    EnrichedGapVRPSolver,
    EnrichedLegacyGapConfig,
    EnrichedLegacyMILPConfig,
    EnrichedMILPDecompConfig,
    EnrichedMILPDecompSolver,
    EnrichedMILPStochasticConfig,
    EnrichedMILPStochasticSolver,
    EnrichedMILPConfig,
    EnrichedMILPSolver,
    EnrichedStochasticConfig,
    EnrichedStochasticGRASPSolver,
    EnrichedStochasticRRSolver,
    benchmark_enriched_algorithms,
    solve_enriched_batched_greedy,
    solve_enriched_gap_vrp,
    solve_enriched_legacy_gap_vrp,
    solve_enriched_legacy_milp,
    solve_enriched_milp_adaptive_hardness,
    solve_enriched_milp_ablation_adaptive_k,
    solve_enriched_milp_ablation_baseline,
    solve_enriched_milp_ablation_penalty_sweep,
    solve_enriched_milp_ablation_portfolio,
    solve_enriched_milp_ablation_zone_bundle,
    solve_enriched_milp_batch_cascaded,
    solve_enriched_milp_batch_portfolio,
    solve_enriched_milp_batch_then_milp,
    solve_enriched_milp_critical_first,
    solve_enriched_milp_hybrid_seeded,
    solve_enriched_milp_lexicographic_2stage,
    solve_enriched_milp_lns_rounds,
    solve_enriched_milp_time_windowed,
    solve_enriched_milp_zone_quota,
    solve_enriched_milp_decomposed,
    solve_enriched_milp_stochastic,
    solve_enriched_milp,
    solve_enriched_stochastic_grasp,
    solve_enriched_stochastic_rr,
)

__all__ = [
    "DummySolverResult",
    "run_dummy_solver",
    "GapVRPALNSSolution",
    "GapVRPSAASolution",
    "SolverResult",
    "run_gap_vrp",
    "select_agents_subset",
    "run_baseline_greedy",
    "compare_methods",
    "assign_tasks_genetic",
    "assign_tasks_greedy",
    "solve_sandbox_milp",
    "solve_real_gap_vrp",
    "solve_real_gap_vrp_alns",
    "solve_real_gap_vrp_saa",
    "solve_real_genetic",
    "solve_real_milp",
    "solve_real_milp_ksenya",
    "solve_real_milp_ksenya_decomp",
    "solve_real_milp_ksenya_knn",
    "solve_real_milp_ksenya_decomp_knn",
    "solve_real_stochastic_grasp",
    "solve_real_stochastic_rr",
    "EnrichedGapVRPConfig",
    "EnrichedGapVRPSolver",
    "EnrichedLegacyGapConfig",
    "EnrichedLegacyMILPConfig",
    "EnrichedMILPDecompConfig",
    "EnrichedMILPDecompSolver",
    "EnrichedMILPStochasticConfig",
    "EnrichedMILPStochasticSolver",
    "EnrichedMILPConfig",
    "EnrichedMILPSolver",
    "EnrichedStochasticConfig",
    "EnrichedStochasticGRASPSolver",
    "EnrichedStochasticRRSolver",
    "benchmark_enriched_algorithms",
    "solve_enriched_batched_greedy",
    "solve_enriched_gap_vrp",
    "solve_enriched_legacy_gap_vrp",
    "solve_enriched_legacy_milp",
    "solve_enriched_milp_adaptive_hardness",
    "solve_enriched_milp_ablation_adaptive_k",
    "solve_enriched_milp_ablation_baseline",
    "solve_enriched_milp_ablation_penalty_sweep",
    "solve_enriched_milp_ablation_portfolio",
    "solve_enriched_milp_ablation_zone_bundle",
    "solve_enriched_milp_batch_cascaded",
    "solve_enriched_milp_batch_portfolio",
    "solve_enriched_milp_batch_then_milp",
    "solve_enriched_milp_critical_first",
    "solve_enriched_milp_hybrid_seeded",
    "solve_enriched_milp_lexicographic_2stage",
    "solve_enriched_milp_lns_rounds",
    "solve_enriched_milp_time_windowed",
    "solve_enriched_milp_zone_quota",
    "solve_enriched_milp_decomposed",
    "solve_enriched_milp_stochastic",
    "solve_enriched_milp",
    "solve_enriched_stochastic_grasp",
    "solve_enriched_stochastic_rr",
]
